name: Test

on:
  push:
    branches: [ develop, master ]
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'example/**'
      - 'zstd.nimble'
      - 'zstd/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  test:
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nim:
          - '1.2.x'
          - '1.4.x'
          - '1.6.x'
          - '2.0.x'
          - 'stable'
        os:
          - ubuntu-latest
          - macOS-latest

    name: Test on ${{ matrix.nim }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble test --verbose


